### ISSUE TITLE
Proxy PuppetDB Dashboard does not work with selinux in enforcing mode

### ISSUE THREAD

**Issue by edestecd** [theforeman/puppetdb_foreman#15]
It crashes with a 500 error when selinux is enabled in CentOS 7.1.
I need to do some further investigating to determine what may bee needed here.

Not sure exactly where to add selinux rules for this plugin?  In the main foreman selinux?

**Comment by edestecd** [comment]
This can be fixed by setting the passenger_can_connect_all selinux boolean:
http://projects.theforeman.org/issues/12991

I manage my puppet master / foreman instance with puppet and have added this to fix it:

```puppet
# puppet/selinux.pp
# Manage selinux setting needed by puppet master
#   connect to puppetdb and dashboard
#

class profile::puppet::selinux {

  # Allow passenger / puppet to connect to puppetdb and puppetdb dashboard
  if str2bool($::selinux) {
    selboolean { 'passenger_can_connect_all':
      persistent => true,
      value      => 'on',
    }
  }
}
```

Maybe this should go in the doc / README.
There may also be a better way to do this in the OS packages for selinux policy.

**Comment by alexjfisher** [comment]
For the benefit of anyone who stumbles across this issue whilst trying to get Foreman 2.x to work with PuppetDB and SELinux...

Even though the puppetdb dashboard doesn't exist anymore, to get `PuppetDB Nodes` to work with SELinux on modern versions of Foreman, use the `foreman_rails_can_connect_all` selinux boolean instead of `passenger_can_connect_all`.
